{
 "title": "Nginx metrics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Latency 0.5 quantile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le, path) (rate(nginx_ingress_controller_response_duration_seconds_bucket[1m])))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Latency 0.95 quantile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, path) (rate(nginx_ingress_controller_response_duration_seconds_bucket[1m])))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Latency 0.99 quantile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, path) (rate(nginx_ingress_controller_response_duration_seconds_bucket[1m])))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Latency Max",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(max by (path) (rate(nginx_ingress_controller_response_duration_seconds_bucket[1m])))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (endpoint) (rate(nginx_ingress_controller_nginx_process_requests_total[1m]))",
     "legendFormat": "{{ endpoint }}"
    },
    {}
   ]
  },
  {
   "title": "Error rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (increase(nginx_ingress_controller_request_duration_seconds_count{status=~\"5.+\"}[1m]))"
    }
   ]
  }
 ]
}