{
 "title": "App metrics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Latency 0.5 quantile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le, exported_endpoint) (rate(app_request_latency_seconds_bucket[1m])))",
     "legendFormat": "{{ exported_endpoint }} latency"
    }
   ]
  },
  {
   "title": "Latency 0.95 quantile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, exported_endpoint) (rate(app_request_latency_seconds_bucket[1m])))",
     "legendFormat": "{{ exported_endpoint }} latency"
    }
   ]
  },
  {
   "title": "Latency 0.99 quantile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, exported_endpoint) (rate(app_request_latency_seconds_bucket[1m])))",
     "legendFormat": "{{ exported_endpoint }}"
    }
   ]
  },
  {
   "title": "Latency Max",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(max by (exported_endpoint) (rate(app_request_latency_seconds_bucket[1m])))",
     "legendFormat": "{{ exported_endpoint }}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_endpoint) (rate(app_request_count_total[1m]))",
     "legendFormat": "{{ exported_endpoint }} rps"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (http_status) (increase(app_request_count_total{http_status=~\"5.+\"}[1m]))",
     "legendFormat": "{{ http_status }}"
    }
   ]
  },
  {
   "title": "Pods CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{container=\"otusapp-chart\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Pods RAM",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container=\"otusapp-chart\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}