prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
# graphana:
#   sidecar:
#     dashboards:
#       enabled: true
#       label: grafana
