apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otusapp-chart.fullname" . }}
  labels:
    {{- include "otusapp-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "otusapp-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "otusapp-chart.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: SQLALCHEMY_DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: otusapp-secret
                  key: SQLALCHEMY_DATABASE_URI
            - name: GREETING
              valueFrom:
                configMapKeyRef:
                  name: otusapp-config
                  key: GREETING

          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 1

          readinessProbe:
            httpGet:
              path: /health/
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5
