apiVersion: v1
kind: Secret
metadata:
  name: otusapp-secret
type: Opaque
data:
  SQLALCHEMY_DATABASE_URI: {{ printf "postgresql+psycopg2://%s:%s@%s:%d/%s" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword (include "postgresql.fullname" .) (.Values.postgresql.service.port | int) .Values.postgresql.postgresqlDatabase | b64enc | quote }}
