apiVersion: v1
kind: Service
metadata:
  name: {{ include "otusapp-chart.fullname" . }}
  labels:
    {{- include "otusapp-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      name: web
      targetPort: http
      nodePort: 30800
  selector:
    {{- include "otusapp-chart.selectorLabels" . | nindent 4 }}
