"""create users table

Revision ID: 8d140db8f782
Revises: 
Create Date: 2020-10-30 13:10:28.628435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d140db8f782'
down_revision = None
branch_labels = ('default',)
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=63), nullable=False),
    sa.Column('first_name', sa.String(length=127), nullable=True),
    sa.Column('last_name', sa.String(length=127), nullable=True),
    sa.Column('email', sa.String(length=127), nullable=False),
    sa.Column('phone', sa.String(length=31), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
